import {Project} from "./types";

export const projects: Project[] = [
  {
    id: 1,
    name: "Eliada the second",
    progress: 50,
    client: "Claudio Conceicao",
    priority: "Medium",
    status: "em-curso",
    dueDate: "15 de Junho",
    location: "Luanda",
  },
  {
    id: 2,
    name: "Patriota View",
    progress: 90,
    client: "Ilda",
    priority: "High",
    status: "concluido",
    dueDate: "20 de Junho",
    location: "Benguela",
  },
  {
    id: 3,
    name: "Talatona Tower",
    client: "Eliene dos Santos",
    progress: 15,
    priority: "Medium",
    status: "em-observacao",
    dueDate: "30 de Julho",
    location: "Huambo",
  },
  {
    id: 4,
    name: "Marina Bay",
    client: "Pedro Joao",
    progress: 15,
    priority: "High",
    status: "em-observacao",
    dueDate: "30 de Julho",
    location: "Huambo",
  },
  {
    id: 5,
    name: "Imgombota Chamber",
    client: "Carlos Jose",
    progress: 54,
    priority: "Low",
    status: "em-observacao",
    dueDate: "30 de Julho",
    location: "Huambo",
  },
];